#!/usr/bin/env bash
#
# make_app.sh - 把 swift build 产物打包成 AudioNote.app
#
# 用法：
#   ./scripts/make_app.sh                # 默认 release，输出到 build/AudioNote.app
#   ./scripts/make_app.sh debug          # debug 配置（更快但更大）
#   APP_OUT_DIR=~/Desktop ./scripts/make_app.sh   # 自定义输出目录
#   NO_BUMP=1 ./scripts/make_app.sh      # 试打包，不自动递增 VERSION
#
# 版本号：
#   ./VERSION 保存当前 marketing version（X.Y.Z）
#   打包时：
#     CFBundleShortVersionString = VERSION 内容（例 1.0.1）
#     CFBundleVersion            = ${VERSION}_YYYY/MM/DD_HH:MM:SS
#   打包成功后自动把 VERSION 的 patch +1（下次再打就是 1.0.2）
#
# 产物结构：
#   AudioNote.app/
#   ├── Contents/
#   │   ├── Info.plist              (from Resources/Info.plist)
#   │   ├── MacOS/AudioNote         (swift build 产物)
#   │   └── Resources/
#   │       ├── AppIcon.icns        (from Resources/AppIcon.icns)
#   │       ├── scripts/
#   │       │   └── transcribe.py   (从仓库 scripts/ 拷贝)
#   │       └── vendor/
#   │           └── ffmpeg          (从仓库 vendor/ 拷贝，需先 ./scripts/fetch_vendor.sh)
#
# 退出码：
#   0 - 成功
#   1 - 缺依赖（vendor/ffmpeg 不存在等）
#   2 - swift build 失败
#

set -euo pipefail

# ---- 路径 ----
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG="${1:-release}"
OUT_DIR="${APP_OUT_DIR:-$REPO_ROOT/build}"
APP_NAME="AudioNote"
APP_BUNDLE="$OUT_DIR/$APP_NAME.app"

cd "$REPO_ROOT"

# ---- 前置检查 ----
if [ ! -f "Resources/AppIcon.icns" ]; then
    echo "❌ Resources/AppIcon.icns 不存在" >&2
    exit 1
fi

if [ ! -f "Resources/Info.plist" ]; then
    echo "❌ Resources/Info.plist 不存在" >&2
    exit 1
fi

if [ ! -f "vendor/ffmpeg" ]; then
    echo "❌ vendor/ffmpeg 不存在，请先运行：./scripts/fetch_vendor.sh" >&2
    exit 1
fi

if [ ! -f "scripts/transcribe.py" ]; then
    echo "❌ scripts/transcribe.py 不存在" >&2
    exit 1
fi

# ---- 0. 读取 VERSION (build 前，用于注入 GUI plist 和 CLI Version.swift) ----
VERSION_FILE="$REPO_ROOT/VERSION"
if [ ! -f "$VERSION_FILE" ]; then
    echo "0.3.0" > "$VERSION_FILE"
fi
CURRENT_VERSION="$(tr -d '[:space:]' < "$VERSION_FILE")"

# 生成 Version.swift 让 CLI/引擎引用 VERSION（单源真相）
VERSION_SWIFT="$REPO_ROOT/Sources/AudioNoteCore/Core/Version.swift"
printf '// Auto-generated by make_app.sh from VERSION file — do not edit manually.\npublic enum AppVersion {\n    public static let current = "%s"\n}\n' "$CURRENT_VERSION" > "$VERSION_SWIFT"

# ---- 1. swift build ----
# --disable-sandbox：避免某些环境下 SwiftPM 的 manifest sandbox-exec 拿不到权限
echo "🔨 swift build -c $CONFIG ..."
if ! swift build -c "$CONFIG" --disable-sandbox; then
    echo "❌ swift build 失败" >&2
    exit 2
fi

BIN_PATH="$(swift build -c "$CONFIG" --disable-sandbox --show-bin-path)/$APP_NAME"
if [ ! -x "$BIN_PATH" ]; then
    echo "❌ 找不到产物: $BIN_PATH" >&2
    exit 2
fi

# ---- 2. 清理旧 bundle ----
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources/scripts"
mkdir -p "$APP_BUNDLE/Contents/Resources/vendor"

# ---- 3. 拷贝二进制 ----
echo "📦 拷贝 MacOS/AudioNote ..."
cp "$BIN_PATH" "$APP_BUNDLE/Contents/MacOS/$APP_NAME"
chmod +x "$APP_BUNDLE/Contents/MacOS/$APP_NAME"

# ---- 4. 拷贝资源 ----
echo "📦 拷贝 Info.plist / AppIcon.icns ..."
cp "Resources/Info.plist" "$APP_BUNDLE/Contents/Info.plist"
cp "Resources/AppIcon.icns" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"

# ---- 4.1 注入版本号到 GUI plist ----
# VERSION 已在 step 0 读取；CFBundleVersion 附加 build 时间戳
BUILD_STAMP="$(date '+%Y/%m/%d_%H:%M:%S')"
BUILD_VERSION="${CURRENT_VERSION}_${BUILD_STAMP}"

printf '[version] CFBundleShortVersionString=%s  CFBundleVersion=%s\n' "$CURRENT_VERSION" "$BUILD_VERSION"
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $CURRENT_VERSION" "$APP_BUNDLE/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_VERSION" "$APP_BUNDLE/Contents/Info.plist"

echo "📦 拷贝 scripts/transcribe.py ..."
cp "scripts/transcribe.py" "$APP_BUNDLE/Contents/Resources/scripts/transcribe.py"

echo "📦 拷贝 vendor/ffmpeg ..."
cp "vendor/ffmpeg" "$APP_BUNDLE/Contents/Resources/vendor/ffmpeg"
chmod +x "$APP_BUNDLE/Contents/Resources/vendor/ffmpeg"

# ---- 5. 代码签名（ad-hoc） ----
echo "🔏 代码签名（ad-hoc）..."
codesign --force --deep --sign - "$APP_BUNDLE" 2>&1 | grep -v "replacing existing signature" || true

# ---- 6. 打包成功后递增 VERSION 的 patch 号 ----
# 规则：仅在 marketing version 形如 X.Y.Z 时自动 +1 patch；NO_BUMP=1 跳过
if [ "${NO_BUMP:-0}" != "1" ]; then
    NEXT_VERSION="$(printf '%s' "$CURRENT_VERSION" | awk -F. '{
        if (NF==3 && $1 ~ /^[0-9]+$/ && $2 ~ /^[0-9]+$/ && $3 ~ /^[0-9]+$/) {
            printf "%s.%s.%d", $1, $2, $3+1
        }
    }')"
    if [ -n "$NEXT_VERSION" ]; then
        echo "$NEXT_VERSION" > "$VERSION_FILE"
        printf '[bump] VERSION 已递增：%s -> %s（下次打包用）\n' "$CURRENT_VERSION" "$NEXT_VERSION"
        # 同步更新 Version.swift，确保直接 swift build 也能拿到正确版本
        printf '// Auto-generated by make_app.sh from VERSION file — do not edit manually.\npublic enum AppVersion {\n    public static let current = "%s"\n}\n' "$NEXT_VERSION" > "$VERSION_SWIFT"
    else
        printf '[warn] VERSION 文件内容（%s）不是 X.Y.Z 格式，跳过自动递增\n' "$CURRENT_VERSION" >&2
    fi
else
    echo "ℹ️  NO_BUMP=1，跳过 VERSION 递增"
fi

# ---- 7. 完成 ----
SIZE=$(du -sh "$APP_BUNDLE" | awk '{print $1}')
echo ""
echo "✅ 打包完成"
echo "   路径: $APP_BUNDLE"
echo "   大小: $SIZE"
echo "   版本: $CURRENT_VERSION  (build: $BUILD_VERSION)"
echo ""
echo "   用法："
echo "     open '$APP_BUNDLE'"
echo "     或拖到 /Applications"
